#!/bin/bash

mkdir -p /var/homepass-pi
cd /var/homepass-pi

if [ ! -s macaddr-list ]; then
	sort --random-sort /etc/homepass-pi/macaddr-list > macaddr-list
fi

macaddr=`head -n 1 macaddr-list`

tail -n +2 macaddr-list > macaddr-tail
rm -f macaddr-list
mv macaddr-tail macaddr-list

cat << EOF > hostapd.conf
interface=wlan0
bridge=br0
driver=nl80211
ssid=attwifi
bssid=$macaddr
hw_mode=g
channel=6
auth_algs=1
wpa=0
macaddr_acl=0
# accept_mac_file=/etc/hostapd/mac_accept
wmm_enabled=0
ignore_broadcast_ssid=0
EOF

killall hostapd
hostapd hostapd.conf


